name: Compile painel.cs using dotnet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Create temp console project
        run: |
          dotnet new console -o tempProj --framework net7.0
          move painel.cs tempProj/Program.cs

      - name: Build project
        run: |
          cd tempProj
          dotnet publish -c Release -r win-x64 --self-contained false -o publish

      - name: Upload compiled exe
        uses: actions/upload-artifact@v4
        with:
          name: painel-exe
          path: tempProj/publish/painel.exe
