name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'icone.ico'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pycryptodome requests

    - name: Detect main script
      id: detect_script
      run: |
        FILE=$(ls *.py | head -n 1)
        echo "main_file=$FILE" >> $GITHUB_ENV
        NAME=$(basename $FILE .py)
        echo "exe_name=$NAME.exe" >> $GITHUB_ENV

    - name: Build EXE
      run: |
        pyinstaller --onefile --icon icone.ico "$env:main_file"
        Rename-Item "dist/$env:main_file" "dist/$env:exe_name"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/*.exe
