name: Build PainelCity EXE (cross-compile)

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar cross-compiler e libs Windows
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 \
            mingw-w64-x86-64-dev \
            mingw-w64-x86-64-openssl-dev

      - name: Compilar PainelCity.exe
        run: |
          x86_64-w64-mingw-g++ painelcity.cpp \
            -std=c++17 \
            -Iinclude \
            -lssl -lcrypto -lcrypt32 \
            -o PainelCity.exe

      - uses: actions/upload-artifact@v4
        with:
          name: painelcity-exe
          path: PainelCity.exe
