name: Build PainelCity EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Compilar PainelCity.exe com cl.exe
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
          cl painelcity.cpp /EHsc /std:c++17 /Fe:PainelCity.exe

      - name: Upload do executável
        uses: actions/upload-artifact@v4
        with:
          name: painelcity-exe
          path: PainelCity.exe
