name: Compile painel.cs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile painel.cs
        run: |
          dir
          csc painel.cs
          dir

      - name: Upload compiled exe
        uses: actions/upload-artifact@v3
        with:
          name: painel-exe
          path: painel.exe
