name: Build Windows exe

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'icone.ico'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pycryptodome requests

    - name: Detect main script
      id: detect_script
      run: |
        $file = Get-ChildItem *.py | Select-Object -First 1
        echo "main_file=$($file.Name)" >> $env:GITHUB_ENV
        $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        echo "exe_name=$name.exe" >> $env:GITHUB_ENV

    - name: Build EXE
      run: |
        pyinstaller --onefile --icon=icone.ico $env:main_file

    - name: Rename EXE
      run: |
        $name = "$env:exe_name"
        Rename-Item -Path "dist/*.exe" -NewName $name

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/*.exe
